"""Add score in ugs

Revision ID: 362876d093d0
Revises: 2f76eb098f1f
Create Date: 2026-02-26 00:54:15.736810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '362876d093d0'
down_revision: Union[str, Sequence[str], None] = '2f76eb098f1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_game_status', sa.Column('score', sa.Integer(), nullable=True))
    op.alter_column('user_game_status', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_game_status', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.drop_column('user_game_status', 'score')
    # ### end Alembic commands ###
