"""add is_admin

Revision ID: 36ba24d28888
Revises: ac8533de78d9
Create Date: 2026-02-24 05:21:00.104800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '36ba24d28888'
down_revision: Union[str, Sequence[str], None] = 'ac8533de78d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'search_vector')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed('(setweight(to_tsvector(\'russian\'::regconfig, (((COALESCE(title, \'\'::character varying))::text || \' \'::text) || COALESCE(description, \'\'::text))), \'A\'::"char") || setweight(to_tsvector(\'english\'::regconfig, (((COALESCE(title, \'\'::character varying))::text || \' \'::text) || COALESCE(description, \'\'::text))), \'B\'::"char"))', persisted=True), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
