"""split game - game_details

Revision ID: aa67eae0d386
Revises: 9a44e8d4064f
Create Date: 2026-02-25 01:27:40.071952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa67eae0d386'
down_revision: Union[str, Sequence[str], None] = '9a44e8d4064f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_details',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('description', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sys_req_min', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sys_req_rec', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('trailer_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_table('game_details')
    # ### end Alembic commands ###
