"""Create all tables from models

Revision ID: ac8533de78d9
Revises: 
Create Date: 2026-02-21 20:34:33.262762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac8533de78d9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('developers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=30), nullable=False),
    sa.Column('founded', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index('idx_developers_title', 'developers', ['title'], unique=False)
    op.create_index(op.f('ix_developers_id'), 'developers', ['id'], unique=False)
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.CheckConstraint('length(name) >= 2', name='check_genres_name_len'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_genres_id'), 'genres', ['id'], unique=False)
    op.create_table('platforms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_platforms_id'), 'platforms', ['id'], unique=False)
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('release_date', sa.Date(), server_default=sa.text('CURRENT_DATE')),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('dev_game', sa.Integer(), nullable=True),
    sa.Column('avg_rating', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('steam_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("release_date > '1940-01-01'", name='check_release_date'),
    sa.CheckConstraint('length(title) >= 2', name='check_title_len'),
    sa.ForeignKeyConstraint(['dev_game'], ['developers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('steam_id'),
    sa.UniqueConstraint('title')
    )
    op.create_index('idx_games_dev_game', 'games', ['dev_game'], unique=False)
    op.create_index('idx_games_release_date', 'games', ['release_date'], unique=False)
    op.create_index('idx_games_steam_id', 'games', ['steam_id'], unique=False)
    op.create_index(op.f('ix_games_id'), 'games', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('pass_hash', sa.String(length=255), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default='NOW()', nullable=True),
    sa.Column('birth', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fav_genre_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("birth > '1900-01-01' AND birth < CURRENT_DATE - INTERVAL '12 years'", name='check_age'),
    sa.CheckConstraint('length(username) >= 3', name='check_username_len'),
    sa.ForeignKeyConstraint(['fav_genre_id'], ['genres.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index('idx_users_fav_genre', 'users', ['fav_genre_id'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('game_genres',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'genre_id')
    )
    op.create_index('idx_game_genres_genre_id', 'game_genres', ['genre_id'], unique=False)
    op.create_index('one_primary_genre_per_game', 'game_genres', ['game_id'], unique=True,
                    postgresql_where="is_primary = true")
    op.create_table('game_platforms',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'platform_id')
    )
    op.create_index('idx_game_platforms_platform_id', 'game_platforms', ['platform_id'], unique=False)
    op.create_table('rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('time_to_score', sa.DateTime(timezone=True), server_default='NOW()', nullable=True),
    sa.CheckConstraint('score >= 0 AND score <= 10', name='check_score'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'game_id', name='unique_user_game')
    )
    op.create_index('idx_rating_game_id', 'rating', ['game_id'], unique=False)
    op.create_index('idx_rating_game_score', 'rating', ['game_id', 'score'], unique=False)
    op.create_index('idx_rating_user_score', 'rating', ['user_id', 'score'], unique=False)
    op.create_index(op.f('ix_rating_id'), 'rating', ['id'], unique=False)
    op.create_table('user_game_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='NOW()', nullable=True),
    sa.CheckConstraint("status IN ('planned', 'playing', 'completed', 'dropped')", name='check_status'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'game_id', name='unique_user_game_status')
    )
    op.create_index('idx_user_game_status_game_status', 'user_game_status', ['game_id', 'status'], unique=False)
    op.create_index('idx_user_game_status_status', 'user_game_status', ['status'], unique=False)
    op.create_index('idx_user_game_status_user_status', 'user_game_status', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_user_game_status_id'), 'user_game_status', ['id'], unique=False)
    op.execute("""
         ALTER TABLE games ADD COLUMN search_vector tsvector
            GENERATED ALWAYS AS (
                setweight(to_tsvector('russian', coalesce(title, '') || ' ' || coalesce(description, '')), 'A') ||
                setweight(to_tsvector('english', coalesce(title, '') || ' ' || coalesce(description, '')), 'B')
            ) STORED;
        """)
    op.execute("""
    CREATE OR REPLACE FUNCTION update_game_avg_rating()
    RETURNS TRIGGER AS $$
    BEGIN
        IF TG_OP = 'DELETE' THEN
            UPDATE games SET avg_rating = (
                SELECT COALESCE(AVG(score), 0) FROM rating WHERE game_id = OLD.game_id
            ) WHERE id = OLD.game_id;
            RETURN OLD;
        ELSE
            UPDATE games SET avg_rating = (
                SELECT COALESCE(AVG(score), 0) FROM rating WHERE game_id = NEW.game_id
            ) WHERE id = NEW.game_id;
            RETURN NEW;
        END IF;
    END;
    $$ LANGUAGE plpgsql;

    CREATE TRIGGER trigger_update_avg_rating
    AFTER INSERT OR DELETE OR UPDATE ON rating
    FOR EACH ROW EXECUTE FUNCTION update_game_avg_rating();
    """)



    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_game_status_id'), table_name='user_game_status')
    op.drop_index('idx_user_game_status_user_status', table_name='user_game_status')
    op.drop_index('idx_user_game_status_status', table_name='user_game_status')
    op.drop_index('idx_user_game_status_game_status', table_name='user_game_status')
    # Удаляем триггер и функцию (если они существуют)
    op.execute("DROP TRIGGER IF EXISTS trigger_update_avg_rating ON rating;")
    op.execute("DROP FUNCTION IF EXISTS update_game_avg_rating();")
    # Удаляем колонку search_vector из таблицы games (если она есть)
    op.execute("ALTER TABLE games DROP COLUMN IF EXISTS search_vector;")
    op.drop_table('user_game_status')
    op.drop_index(op.f('ix_rating_id'), table_name='rating')
    op.drop_index('idx_rating_user_score', table_name='rating')
    op.drop_index('idx_rating_game_score', table_name='rating')
    op.drop_index('idx_rating_game_id', table_name='rating')
    op.drop_table('rating')
    op.drop_index('idx_game_platforms_platform_id', table_name='game_platforms')
    op.drop_table('game_platforms')
    op.drop_index('one_primary_genre_per_game', table_name='game_genres', postgresql_where=sa.text('is_primary = true'))
    op.drop_index('idx_game_genres_genre_id', table_name='game_genres')
    op.drop_table('game_genres')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index('idx_users_fav_genre', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_games_id'), table_name='games')
    op.drop_index('idx_games_steam_id', table_name='games')
    op.drop_index('idx_games_release_date', table_name='games')
    op.drop_index('idx_games_dev_game', table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_platforms_id'), table_name='platforms')
    op.drop_table('platforms')
    op.drop_index(op.f('ix_genres_id'), table_name='genres')
    op.drop_table('genres')
    op.drop_index(op.f('ix_developers_id'), table_name='developers')
    op.drop_index('idx_developers_title', table_name='developers')
    op.drop_table('developers')

