"""delete uniq from game.title

Revision ID: b97ea53250c9
Revises: aa67eae0d386
Create Date: 2026-02-25 02:34:18.416752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b97ea53250c9'
down_revision: Union[str, Sequence[str], None] = 'aa67eae0d386'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('games_title_key'), 'games', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('games_title_key'), 'games', ['title'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
