"""restructer dev

Revision ID: bb2bd44a2485
Revises: b97ea53250c9
Create Date: 2026-02-25 02:36:07.091588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb2bd44a2485'
down_revision: Union[str, Sequence[str], None] = 'b97ea53250c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_developers_title'), table_name='developers')
    op.drop_column('developers', 'country')
    op.drop_column('developers', 'founded')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('developers', sa.Column('founded', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('developers', sa.Column('country', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.create_index(op.f('idx_developers_title'), 'developers', ['title'], unique=False)
    # ### end Alembic commands ###
