"""add price and platforms

Revision ID: d24de318eb23
Revises: 362876d093d0
Create Date: 2026-02-27 16:22:29.356229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd24de318eb23'
down_revision: Union[str, Sequence[str], None] = '362876d093d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('price', sa.Float(), nullable=True))
    op.add_column('games', sa.Column('platforms', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'platforms')
    op.drop_column('games', 'price')
    # ### end Alembic commands ###
