"""add extended fields for user and game

Revision ID: ea12ae3e9115
Revises: 36ba24d28888
Create Date: 2026-02-24 06:20:52.456391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea12ae3e9115'
down_revision: Union[str, Sequence[str], None] = '36ba24d28888'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('cover_url', sa.String(length=255), nullable=True))
    op.add_column('games', sa.Column('trailer_url', sa.String(length=255), nullable=True))
    op.add_column('games', sa.Column('hltb_main', sa.Numeric(precision=5, scale=1), nullable=True))
    op.add_column('games', sa.Column('hltb_completionist', sa.Numeric(precision=5, scale=1), nullable=True))
    op.add_column('games', sa.Column('sys_req_min', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('games', sa.Column('sys_req_rec', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('games', sa.Column('steam_app_id', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('igdb_id', sa.Integer(), nullable=True))
    op.alter_column('games', 'description',
                    existing_type=sa.TEXT(),
                    type_=postgresql.JSONB(astext_type=sa.Text()),
                    postgresql_using="to_jsonb(description)",
                    existing_nullable=True)
    op.drop_constraint(op.f('games_steam_id_key'), 'games', type_='unique')
    op.drop_index(op.f('idx_games_steam_id'), table_name='games')
    op.create_index('idx_games_igdb_id', 'games', ['igdb_id'], unique=False)
    op.create_index('idx_games_steam_app_id', 'games', ['steam_app_id'], unique=False)
    op.create_unique_constraint(None, 'games', ['steam_app_id'])
    op.create_unique_constraint(None, 'games', ['igdb_id'])
    op.drop_column('games', 'steam_id')
    op.add_column('users', sa.Column('avatar_url', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('show_age', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('steam_id', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('discord_id', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'users', ['discord_id'])
    op.create_unique_constraint(None, 'users', ['steam_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'discord_id')
    op.drop_column('users', 'steam_id')
    op.drop_column('users', 'show_age')
    op.drop_column('users', 'avatar_url')
    op.add_column('games', sa.Column('steam_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'games', type_='unique')
    op.drop_constraint(None, 'games', type_='unique')
    op.drop_index('idx_games_steam_app_id', table_name='games')
    op.drop_index('idx_games_igdb_id', table_name='games')
    op.create_index(op.f('idx_games_steam_id'), 'games', ['steam_id'], unique=False)
    op.create_unique_constraint(op.f('games_steam_id_key'), 'games', ['steam_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('games', 'description',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('games', 'igdb_id')
    op.drop_column('games', 'steam_app_id')
    op.drop_column('games', 'sys_req_rec')
    op.drop_column('games', 'sys_req_min')
    op.drop_column('games', 'hltb_completionist')
    op.drop_column('games', 'hltb_main')
    op.drop_column('games', 'trailer_url')
    op.drop_column('games', 'cover_url')
    # ### end Alembic commands ###
