"""split game - game_details

Revision ID: fa83a82609de
Revises: 9a44e8d4064f
Create Date: 2026-02-25 01:19:01.854367

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a44e8d4064f'
down_revision: Union[str, Sequence[str], None] = 'ea12ae3e9115'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'description')
    op.drop_column('games', 'trailer_url')
    op.drop_column('games', 'sys_req_min')
    op.drop_column('games', 'sys_req_rec')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('sys_req_rec', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('games', sa.Column('sys_req_min', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('games', sa.Column('trailer_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('games', sa.Column('description', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
