from .user import User
from .genre import Genre
from .developers import Developer
from .game import Game
from .platform import Platform
from .rating import Rating
from .user_game_status import UserGameStatus
from .game_genre import GameGenre
from .game_platform import GamePlatform